### ISSUE TITLE
Provide information about standard authorization server

### ISSUE THREAD

**Issue by aertmann** [oktadev/okta-react-native-app-auth-example#3]
Hi @mraible,

First of, thanks a lot for providing this example.

To actually use this example I ran into some issues that I was fortunately able to resolve, but would imagine other people would face the same problem.

I've commented on your blog post https://developer.okta.com/blog/2018/03/16/build-react-native-authentication-oauth-2#comment-4186527336, maybe it would be good to mention in the repository and blog post itself?

Best,
Aske

**Comment by mraible** [comment]
Hello Aske - using your Org's AS is not the recommended setup since you won't be able to validate access token. I've responded to the comment on my blog post and I'm closing this issue.
